### Problem Solution 1

In [12]:
import numpy as np

array = np.random.randint(1,20, (5,5))



In [19]:
array[:, 2]

array([ 3,  7,  8, 15,  7])

### Problem Solution 1.2

In [20]:
array = np.random.randint(1,16, (4,4))

In [35]:
for i in range(len(array)):
    array[i, i] = 0

array

array([[ 0,  9,  8, 13],
       [ 1,  0, 12,  7],
       [10, 11,  0, 10],
       [ 5, 15, 12,  0]])

### Problem Solution 2

In [37]:
array = np.random.randint(1,36, (6,6))
array

array([[ 6, 35, 20, 24, 17, 22],
       [32,  9, 20, 25, 12, 15],
       [13, 25,  9,  9, 21,  1],
       [22, 11, 29,  5, 30, 33],
       [20, 19,  3, 21, 11, 35],
       [35,  3,  2, 23, 12,  8]])

In [39]:
array[3:5, 2:4]

array([[29,  5],
       [ 3, 21]])

### Problem Solution 2.2

In [40]:
array = np.random.randint(1,10, (5,5))
array

array([[9, 1, 2, 1, 5],
       [1, 9, 4, 1, 8],
       [3, 2, 8, 7, 5],
       [7, 7, 4, 2, 6],
       [1, 3, 8, 1, 6]])

In [41]:
array[:, -1]

array([5, 8, 5, 6, 6])

### Problem Solution 3

In [42]:
array1 = np.random.randint(1,10, (3,4))
array2 = np.random.randint(1,10, (3,4))

In [43]:
array1

array([[5, 7, 5, 1],
       [9, 7, 5, 2],
       [2, 3, 1, 4]])

In [44]:
array2

array([[4, 4, 5, 7],
       [7, 8, 4, 3],
       [1, 5, 4, 4]])

In [45]:
array1 + array2

array([[ 9, 11, 10,  8],
       [16, 15,  9,  5],
       [ 3,  8,  5,  8]])

In [46]:
array1 -array2

array([[ 1,  3,  0, -6],
       [ 2, -1,  1, -1],
       [ 1, -2, -3,  0]])

In [47]:
array1 * array2

array([[20, 28, 25,  7],
       [63, 56, 20,  6],
       [ 2, 15,  4, 16]])

In [48]:
array1 / array2

array([[1.25      , 1.75      , 1.        , 0.14285714],
       [1.28571429, 0.875     , 1.25      , 0.66666667],
       [2.        , 0.6       , 0.25      , 1.        ]])

### Problem Solution 3.2

In [49]:
array = np.random.randint(1,16, (4,4))
array

array([[11, 13,  8,  5],
       [12,  5,  1,  4],
       [ 2,  4, 10, 15],
       [ 2,  6,  7, 15]])

In [55]:
for i in range(len(array)):
    print(array[i, :] + array[:, i])

[22 25 10  7]
[25 10  5 10]
[10  5 20 22]
[ 7 10 22 30]


### Problem Solution 4

In [56]:
array = np.random.randint(1,10, (5,5))
array

array([[8, 8, 3, 6, 6],
       [1, 5, 1, 1, 3],
       [9, 8, 6, 8, 3],
       [6, 3, 6, 9, 9],
       [2, 3, 9, 8, 5]])

In [62]:
print(np.mean(array))
print(np.median(array))
print(np.std(array))
print(np.var(array))

5.44
6.0
2.728809264129686
7.4464


### Problem Solution 4.2

In [77]:
array = np.random.randint(1,9, (3,3))
mean = np.mean(array)
std = np.std(array)

normalized_array = ((array - mean) / std)

In [79]:
normalized_array

array([[-0.80178373,  1.20267559, -0.40089186],
       [ 0.        , -1.60356745,  0.80178373],
       [-1.20267559,  0.80178373,  1.20267559]])

In [78]:
print(np.mean(normalized_array))
print(np.std(normalized_array))

0.0
1.0
